const langObj = {
  'en': {
    'name': 'Ivan Kasenka',
    'contacts': 'Contacts',
    'about-myself': 'About myself',
    'education': 'Education',
    'languages': 'Languages',
    'skills': 'Skills',
    'work-experience': 'Work Experience',
    'portfolio': 'Portfolio',
    'about': "I'm 25 years old and I came from Belarus, city of Brest. Nowadays I continue to develop my technical skills. I think ability to learn is one of my strongest features. As a perfectionist I am trying to complete my projects correctly and strictly. Also I am a quick learner and a team worker that gets the job done.",
    'language-1': 'Belarusian - Native',
    'language-2': 'Russian - Native',
    'language-3': 'English - Intermediate',
    'skill-1': 'Knowledge of HTML5, CSS3/SASS, JavaScript, Git, GitHub;',
    'skill-2': 'Worked with Webpack, npm, eslint;',
    'skill-3': 'Experience in cross-browser&adaptive website coding;',
    'skill-4': 'Adherence to the principles of DRY, KISS, YAGNI;',
    'skill-5': 'Understanding the basics of OOP;',
    'skill-6': 'Web site development experience using Visual Studio Code.',
    'education-1-title': 'Bachelor of Computer Science',
    'education-1-subtitle': 'from Brest State Technical University',
    'education-1-time': '2015 - 2020',
    'education-1-li-1': 'Specialty: artificial intelligence',
    'education-1-li-2': 'Qualification: system engineer',
    'work-1-title': 'Database administrator',
    'work-1-subtitle': 'at Inspectorate of the Ministry of Taxes and Duties',
    'work-1-time': 'Aug, 2020 - Aug, 2023',
    'work-1-li-1': 'Software maintenance;',
    'work-1-li-2': 'Database health monitoring;',
    'work-1-li-3': 'Work with developers on issues of interaction with software;',
    'work-1-li-4': 'Working with databases using SQL.',
    'project-1__title': 'Shelter',
    'project-1__description': 'Landing page',
    'project-2__title': 'Minesweeper',
    'project-2__description': 'Small app for fun.',
    'project-3__title': 'Virtual keyboard',
    'project-3__description': 'Small app for fun.',
  },
  'ru': {
    'name': 'Иван Косенко',
    'contacts': 'Контакты',
    'about-myself': 'Обо мне',
    'education': 'Образование',
    'languages': 'Языки',
    'skills': 'Навыки',
    'work-experience': 'Опыт работы',
    'portfolio': 'Портфолио',
    'about': 'Мне 25 лет и я родом из Беларуси , города Бреста. С каждым днем я продолжаю усовершенствовать свои технические навыки. По моему мнению  способность обучаться и легко усваивать полученную информацию - одна из моих сильных качеств. Будучи перфекционистом я прикладываю все усилия для того, чтобы моя работа была выполнена качественно и точно. Также я способен быстро обучаться и работать в команде.',
    'language-1': 'Белорусский - Родной',
    'language-2': 'Русский - Родной',
    'language-3': 'Английский - Пороговый уровень',
    'skill-1': 'Знание HTML5, CSS3/SASS, JavaScript, Git, GitHub;',
    'skill-2': 'Работал с Webpack, npm, eslint;',
    'skill-3': 'Опыт кроссбраузерной и адаптивной верстки сайтов;',
    'skill-4': 'Соблюдение принципов DRY, KISS, YAGNI;',
    'skill-5': 'Понимание основ ООП;',
    'skill-6': 'Опыт разработки веб-сайтов с использованием Visual Studio Code.',
    'education-1-title': 'Бакалавр компьютерных наук',
    'education-1-subtitle': 'Брестского государственного технического университета',
    'education-1-time': '2015 - 2020',
    'education-1-li-1': 'Специальность: искусственный интеллект',
    'education-1-li-2': 'Квалификация: инженер - системотехник',
    'work-1-title': 'Администратор баз данных',
    'work-1-subtitle': 'в инспекции Министерства по налогам и сборам',
    'work-1-time': 'Авг, 2020 - Авг, 2023',
    'work-1-li-1': 'Сопровождение программного обеспечения;',
    'work-1-li-2': 'Мониторинг работоспособности базы данных;',
    'work-1-li-3': 'Работа с разработчиками по вопросам взаимодействия с ПО;',
    'work-1-li-4': 'Работа с базами данных посредством SQL.',
    'project-1__title': 'Приют для животных',
    'project-1__description': 'Лендинг',
    'project-2__title': 'Сапёр',
    'project-2__description': 'Небольшое приложение забавы ради',
    'project-3__title': 'Виртуальная клавиатура',
    'project-3__description': 'Небольшое приложение забавы ради',
  }
}
export default langObj;