const langObj = {
  'en': {
    'name': 'Ivan Kasenka',
    'contacts': 'Contacts',
    'about-myself': 'About myself',
    'education': 'Education',
    'languages': 'Languages',
    'skills': 'Skills',
    'work-experience': 'Work Experience',
    'portfolio': 'Portfolio',
    'about': "I'm 26 years old and I come from Belarus, city of Brest. Nowadays I continue to develop my technical skills. I think ability to learn is one of my strongest features. As a perfectionist I am trying to complete my projects correctly and strictly. Also I am a quick learner and a team worker who gets the job done.",
    'language-1': 'Belarusian - Native',
    'language-2': 'Russian - Native',
    'language-3': 'English - Intermediate',
    'skill-1': 'Сonfident knowledge of HTML5, CSS3, JavaScript(ES6+), Git, GitHub;',
    'skill-1.1': 'Experience of layout of layouts from Figma;',
    'skill-2': 'Able to work with with Webpack, npm, eslint;',
    'skill-3': 'Experience in cross-browser&adaptive website coding;',
    'skill-4': 'Adherence to the principles of SOLID, DRY, KISS, YAGNI;',
    'skill-5': 'Understanding the basics of OOP;',
    'skill-6': 'Basic knowledge of the React library, AntD UI framework;',
    'skill-7': 'Web site development experience using Visual Studio Code;',
    'skill-8': 'Worked with the JIRA project management system.',
    'education-1-title': 'Bachelor of Computer Science',
    'education-1-subtitle': 'from Brest State Technical University',
    'education-1-time': '2015 - 2020',
    'education-1-li-1': 'Speciality: artificial intelligence;',
    'education-1-li-2': 'Qualification: system engineer;',
    'education-1-li-3': 'Diploma project: a convolutional neural network was trained that recognized, from a car recorder camera, dividing strips on roads, classified them and notified the driver about leaving the lane.',
    'work-1-title': 'Database administrator',
    'work-1-subtitle': 'at Inspectorate of the Ministry of Taxes and Duties',
    'work-1-time': 'Aug, 2020 - Aug, 2023',
    'work-1-li-1': 'Accompanied the internal software;',
    'work-1-li-2': 'Monitored database health;',
    'work-1-li-3': 'Worked with developers on issues of interaction, testing and implementation of software;',
    'work-1-li-4': 'Worked with databases using SQL queries;',
    'work-1-li-5': 'Processed program errors and provided them to software developers;',
    'work-1-li-6': 'Accompanied work places.',
    'project-1__title': 'Shelter',
    'project-1__description': 'Landing page',
    'project-2__title': 'Minesweeper',
    'project-2__description': 'Small app for fun.',
    'project-3__title': 'Virtual keyboard',
    'project-3__description': 'Small app for fun.',
  },
  'ru': {
    'name': 'Иван Косенко',
    'contacts': 'Контакты',
    'about-myself': 'Обо мне',
    'education': 'Образование',
    'languages': 'Языки',
    'skills': 'Навыки',
    'work-experience': 'Опыт работы',
    'portfolio': 'Портфолио',
    'about': 'Мне 26 лет и я родом из Беларуси , города Бреста. С каждым днем я продолжаю усовершенствовать свои технические навыки. По моему мнению  способность обучаться и легко усваивать полученную информацию - одна из моих сильных качеств. Будучи перфекционистом я прикладываю все усилия для того, чтобы моя работа была выполнена качественно и точно. Также я способен быстро обучаться и работать в команде.',
    'language-1': 'Белорусский - Родной',
    'language-2': 'Русский - Родной',
    'language-3': 'Английский - Продвинутый уровень',
    'skill-1': 'Уверенные знания HTML5, CSS3, JavaScript(ES6+), Git, GitHub;',
    'skill-1.1': 'Опыт верстки макетов из Figma;',
    'skill-2': 'Работал с Webpack, npm, eslint;',
    'skill-3': 'Опыт кроссбраузерной и адаптивной верстки сайтов;',
    'skill-4': 'Соблюдение принципов SOLID, DRY, KISS, YAGNI;',
    'skill-5': 'Понимание основ ООП;',
    'skill-6': 'Базовые знания библиотеки React, UI фреймворк AntD;',
    'skill-7': 'Опыт разработки веб-сайтов с использованием Visual Studio Code;',
    'skill-8': 'Работал с системой управления проектами JIRA.',
    'education-1-title': 'Бакалавр компьютерных наук',
    'education-1-subtitle': 'Брестского государственного технического университета',
    'education-1-time': '2015 - 2020',
    'education-1-li-1': 'Специальность: искусственный интеллект;',
    'education-1-li-2': 'Квалификация: инженер - системотехник;',
    'education-1-li-3': 'Дипломный проект: была обучена свёрточная нейронная сеть, которая распозновала, с камеры авторегистратора, разделительные полосы на автомобильных дорогах, классифицировала их и оповещала водителя о съезде с полосы.',
    'work-1-title': 'Администратор баз данных',
    'work-1-subtitle': 'в инспекции Министерства по налогам и сборам',
    'work-1-time': 'Авг, 2020 - Авг, 2023',
    'work-1-li-1': 'Сопровождал внутреннее программное обеспечение;',
    'work-1-li-2': 'Мониторил работоспособность базы данных;',
    'work-1-li-3': 'Работал с разработчиками по вопросам взаимодействия, тестирования и внедрения ПО;',
    'work-1-li-4': 'Работал с базами данных посредством SQL запросов;',
    'work-1-li-5': 'Обрабатывал ошибки программ и предоставлял их разработчикам ПО;',
    'work-1-li-6': 'Сопровождал рабочие места.',
    'project-1__title': 'Приют для животных',
    'project-1__description': 'Лендинг',
    'project-2__title': 'Сапёр',
    'project-2__description': 'Небольшое приложение забавы ради',
    'project-3__title': 'Виртуальная клавиатура',
    'project-3__description': 'Небольшое приложение забавы ради',
  }
}
export default langObj;